### PR TITLE
Adds .python-version file

### PR DESCRIPTION
**Pull request by jjacobskind**
## Problem

Manually switching between python versions when using different repos

## Proposed changes

By adding a `.python-version` file in the root directory, as well as a hook in the developer's shell profile, pyenv can automatically set the correct python version when working in this repo.

Curious to hear if other folks think this would be helpful. I've found myself manually switching between 3.7 and 3.8 when switching between the dbt repo and here

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by pnadolny13** [comment]
Thanks for the PR - I understand the difficulty but it might not be practical since it pins such a specific minor version. I dont have 3.7.10 install but I do have 3.7.7 for example. The way I usually manage my python versions is through my virtual envs, I create them with a specific pyenv version so when I activate the virtual env im also using the python version I need - I have a da3_dbt and a tap_snowflake virtual env so I havent run into this. I'm not arguing this is the cleanest way but its worked for me. I'm curious what @cwatkins989 and @timf-bonobos think also.

**Comment by jjacobskind** [comment]
@pnadolny13 gotcha, that makes sense.

I noticed another repo where .python-version is in .gitignore. Would it make sense to add it there? That way, folks can manage python versions however they wish, without impacting others

**Comment by pnadolny13** [comment]
> @pnadolny13 gotcha, that makes sense.
> 
> I noticed another repo where .python-version is in .gitignore. Would it make sense to add it there? That way, folks can manage python versions however they wish, without impacting others

Yeah I think that would do the trick.

I also found this thread that looks like someone made the same point as me but some people do also version control that file. https://stackoverflow.com/questions/54315206/should-we-gitignore-the-python-version-file. 

I'd still vote to just gitignore it though.

**Comment by timf-bonobos** [comment]
> > @pnadolny13 gotcha, that makes sense.
> > I noticed another repo where .python-version is in .gitignore. Would it make sense to add it there? That way, folks can manage python versions however they wish, without impacting others
> 
> Yeah I think that would do the trick.
> 
> I also found this thread that looks like someone made the same point as me but some people do also version control that file. https://stackoverflow.com/questions/54315206/should-we-gitignore-the-python-version-file.
> 
> I'd still vote to just gitignore it though.

I would do .gitignore. 
It's funny but I just have my venv setup for each project I work in the project so I never think about and it's already part of the .gitignore.

**Review by pnadolny13 — APPROVED** [review]
awesome! thanks

**Pull request merged**
